version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hana_app
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - ./php.conf.ini:/usr/local/etc/php/conf.d/php.conf.ini
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: hana_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: hana_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=oot_hana
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hana_phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - UPLOAD_LIMIT=300M
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /sessions
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    volumes:
      - .data/minio/:/data
    restart: always
    ports:
      - "9003:9003"
    environment:
      - MINIO_ACCESS_KEY=upload
      - MINIO_ROOT_USER=app
      - MINIO_SECRET_KEY=keykeykey
      - MINIO_ROOT_PASSWORD=secretsecret
      - MINIO_REGION=us-east-1
    command: server --console-address :9003 /data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
